AllCops:
  NewCops: enable

#################### Bundler ###############################

#################### Gemspec ###############################

#################### Layout ###########################
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/LineLength:
  Max: 120

#################### Lint ##################################
### Warnings

#################### Metrics ###############################

################## Migration #############################

#################### Naming ##############################

#################### Security ##############################

#################### Style ###############################
